sudo: required
services:
  - docker

#before_install:
#  - docker build -t tontonlaforce/react-app:latest -f Dockerfile.dev .

scripts:
#  - docker run --env CI=true tontonlaforce/react-app:latest npm run test -- --coverage
  - echo $(pwd)

deploy:
  provider: elasticbeanstalk
  regin: us-east-1
  app: docker
  env: Docker-env
  bucket_name: xxx_yyy
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

# before_deploy:
#   - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $REGISTRY_NAME  #docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#   - docker build -t $REGISTRY_NAME/react-app:latest -f Dockerfile .
#   - docker push $REGISTRY_NAME/react-app:latest

# deploy:
#   provider: azure_web_apps
#   username: $AZURE_WA_USERNAME #If AZURE_WA_USERNAME isn't set
#   password: #If AZURE_WA_PASSWORD isn't set
#     secure: $AZURE_WA_PASSWORD
#   site: $AZURE_WA_SITE #If AZURE_WA_SITE isn't set
#   # slot: azure_deployment_slotname
#   on:
#     branch: master
#   #scripts:
#   #  - echo "finish deployment"
