apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-service
spec:
  selector:
    matchLabels:
      app: helloworld-service
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld-service
    spec:
      containers:
        - name: helloworld-service
          image: fhsinchy/hello-kube
          # imagePullPolicy: Never
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels:
    app: helloworld-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: helloworld-service