FROM node:14-alpine as build

WORKDIR /app
ENV BACKEND_API_URL=http://goals-bakend-lb-1259880189.us-east-2.elb.amazonaws.com
COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



