apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: demo-sc
provisioner: kubernetes.io/gce-pd
parameters:
  fstype: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  storageClassName: demo-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: demo-pvc
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/trans-sanctum-394312/regions/us-east1/disks/auth-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: demo-pvc
spec:
  storageClassName: demo-sc
  volumeName: demo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi