apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: users-statefulset
spec:
  selector:
    matchLabels:
      app: users # Label selector that determines which Pods belong to the StatefulSet
                 # Must match spec: template: metadata: labels
  serviceName: users-service
  replicas: 3
  template:
    metadata:
      labels:
        app: users # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: users-api
        image: tontonlaforce/kub-users:latest
        env:
          - name: MONGODB_CONNECTION_URI
            # value: 'mongodb+srv://maximilian:wk4nFupsbntPbB3l@cluster0.ntrwp.mongodb.net/users?retryWrites=true&w=majority'
            value: 'mongodb://testdemodb_exclaimed:8dd3cb5388e13d577c0a0a8947c7d0f463b77606@znd.h.filess.io:27017/testdemodb_exclaimed'
          - name: AUTH_API_ADDRESS
            value: 'auth-service.default:3000'
        volumeMounts:
        - name: efs-vol
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: efs-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName : auth-sc
      resources:
        requests:
          storage: 1Gi
